### ISSUE TITLE
Getting rollup babel transformation issue when trying to run this package

### ISSUE THREAD

**Issue by mrboli** [nuxt-community/module-builder#3]
Using the `@nuxtjs/auth` module, and when I try to use `nuxt-module` on it, it gives the following error:

```
{ Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-
plugin-babel#configuring-babel for more information                                                                                     
    at error (/Users/boli/Dev/servd/servd-pos-web/node_modules/@nuxtjs/auth/node_modules/rollup/dist/rollup.js:185:14) 
    at Object.error (/Users/boli/Dev/servd/servd-pos-web/node_modules/@nuxtjs/auth/node_modules/rollup/dist/rollup.js:9141:6)
    at promise.then.previous (/Users/boli/Dev/servd/servd-pos-web/node_modules/@nuxtjs/auth/node_modules/rollup/dist/rollup.js:9150:32) 
    at <anonymous>                                                                                                                      
    at process._tickCallback (internal/process/next_tick.js:188:7)                                                                      
    at Function.Module.runMain (module.js:667:11)                                                                                       
    at startup (bootstrap_node.js:187:16)                                                                                               
    at bootstrap_node.js:607:3
  code: 'PLUGIN_ERROR',
  plugin: 'babel',
  id: '/Users/boli/Dev/servd/servd-pos-web/node_modules/@nuxtjs/auth/src/index.js' }
```

I've checked that all nuxt-module-builder npm packages are up to date. The lib/rollup.js has:

```
        presets: [
          ['es2015', { modules: false }]
        ],
```

As per: https://github.com/rollup/rollup-plugin-babel/issues/72

Not sure how to resolve this / workaround this.

**Comment by pi0** [comment]
Hi. Are you trying to rebuild auth? Else this is little odd having such error ...

**Comment by mrboli** [comment]
Hey! Thanks for the response.

Yeah, I've forked the `@nuxtjs/auth` module to make changes to how it's being used and to expand on it.

Trying to build it locally so that I don't have to push updates to github each time and update it through npm on my project that I'm consuming it at.

**Comment by mrboli** [comment]
Another reason I would love to have the repo forked is that I would like the ability to make pull requests if I find that I end up writing anything that might be useful to others and expand the usability / flexibility of the module.

**Comment by mrboli** [comment]
@pi0 Another reason I would love to have the repo forked is that I would like the ability to make pull requests if I find that I end up writing anything that might be useful to others and expand the usability / flexibility of the module.
